menu:
    鹏云开发集成指南: /get-started
    Javascript Style Guide: /js-style-guide
    Github: https://github.com/trazyn/hexo-theme-apollo

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:
